/* Colour selection, exact values, persistence, focus and responsive placement. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'test/.out');
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const server = http.createServer((req, res) => {
  const file = path.join(ROOT, req.url.split('?')[0] === '/' ? 'index.html' : decodeURIComponent(req.url.split('?')[0]));
  if (!file.startsWith(ROOT + path.sep) || !fs.existsSync(file) || !fs.statSync(file).isFile()) { res.writeHead(404); return res.end(); }
  res.setHeader('Content-Type', ({ '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css' })[path.extname(file)] || 'application/octet-stream');
  fs.createReadStream(file).pipe(res);
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
let browser;
try {
  browser = await chromium.launch({ headless: true, executablePath: process.env.PLAYWRIGHT_EXECUTABLE_PATH || undefined, ignoreDefaultArgs: ['--hide-scrollbars'], args: ['--enable-unsafe-swiftshader'] });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } }), errors = [];
  page.on('pageerror', e => errors.push(e.message)); await page.route('https://**', r => r.abort());
  const url = `http://127.0.0.1:${server.address().port}/`;
  await page.goto(url); await page.waitForFunction(() => window.stickerApp);
  assert(await page.locator('#ctl-iconFill-picker').isDisabled());
  const id = await page.evaluate(() => stickerApp.addIcon('cloudface', { settings: { iconFill: '#f7c6d4', baseRotation: 0, anim: 'none' } }).id);
  const trigger = page.locator('#ctl-iconFill-picker'), picker = page.locator('#colourPicker'), hex = page.locator('.colour-hex');
  const value = () => page.evaluate(() => stickerApp.selected.settings.iconFill);
  await trigger.click(); assert(await picker.isVisible()); assert.equal(await picker.getAttribute('role'), 'dialog');
  assert.equal(await hex.inputValue(), '#F7C6D4');
  await hex.fill('a3c'); await hex.press('Enter'); assert.equal(await value(), '#aa33cc');
  await hex.fill('#xyzxyz'); await hex.press('Enter'); assert.equal(await hex.getAttribute('aria-invalid'), 'true'); assert.equal(await value(), '#aa33cc');
  await hex.fill('#000000'); await hex.press('Enter');
  await page.locator('.colour-hue').fill('180');
  await page.locator('.colour-sv').focus(); await page.keyboard.press('ArrowUp'); await page.keyboard.press('ArrowRight');
  assert.notEqual(await value(), '#000000', 'keyboard shade adjustment leaves black');
  await hex.fill('#ffffff'); await hex.press('Enter'); await page.locator('.colour-hue').fill('180');
  const box = await page.locator('.colour-sv').boundingBox();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2); await page.mouse.down(); await page.mouse.move(box.x + box.width, box.y, { steps: 5 }); await page.mouse.up();
  assert.equal(await value(), '#00ffff', 'dragging preserves hue while starting from white');
  await page.locator('.colour-rgb input').nth(0).fill('255'); assert.equal(await value(), '#ffffff');
  await page.locator('.colour-rgb input').nth(1).fill('0'); assert.equal(await value(), '#ff00ff');
  await page.locator('.colour-rgb input').nth(2).fill('300'); assert.equal(await value(), '#ff00ff', 'out-of-range RGB is rejected');
  await page.locator('.colour-original').click(); assert.equal(await value(), '#f7c6d4');
  await page.locator('.colour-palette [data-colour="#ccb9ed"]').click(); assert.equal(await value(), '#ccb9ed');
  await page.locator('.colour-done').click(); assert(await picker.isHidden()); assert(await trigger.evaluate(e => e === document.activeElement));
  await page.evaluate(() => stickerApp.undo()); assert.equal(await value(), '#f7c6d4');
  await page.evaluate(() => stickerApp.redo()); assert.equal(await value(), '#ccb9ed');
  await trigger.click(); assert(await page.locator('.colour-recent [data-colour="#ccb9ed"]').isVisible());
  await page.waitForFunction(() => {
    const c = stickerApp.selected.atlas.canvas, d = c.getContext('2d').getImageData(0, 0, c.width, c.height).data;
    let matches = 0; for (let i = 0; i < d.length; i += 4) if (d[i] === 204 && d[i + 1] === 185 && d[i + 2] === 237 && d[i + 3] === 255) matches++;
    return matches > 50;
  });
  fs.mkdirSync(OUT, { recursive: true });
  await page.screenshot({ path: path.join(OUT, 'color-picker-desktop.png') });
  await page.keyboard.press('Escape'); assert(await picker.isHidden());
  await trigger.click(); await page.mouse.click(400, 80); assert(await picker.isHidden(), 'outside click dismisses');
  await page.evaluate(id => stickerApp.scene.select(stickerApp.scene.get(id)), id);
  await trigger.click(); await page.evaluate(id => stickerApp.lockObject(id), id);
  assert(await picker.isHidden()); assert(await trigger.isDisabled());
  await page.evaluate(id => stickerApp.lockObject(id), id);
  await trigger.click(); await page.evaluate(() => stickerApp.addFrame()); assert(await picker.isHidden(), 'selection changes dismiss the old control');
  await page.locator('#ctl-frameColor-picker').click(); await hex.fill('#123456'); await hex.press('Enter');
  assert.equal(await page.evaluate(() => stickerApp.selected.settings.frameColor), '#123456');
  assert(await picker.isVisible(), 'changing a preset colour keeps the picker open');
  await page.keyboard.press('Escape');
  await page.locator('#ctl-background-picker').click(); await hex.fill('#123abc'); await hex.press('Enter');
  assert.equal(await page.evaluate(() => stickerApp.sceneSettings.background), '#123abc'); assert(await picker.isVisible());
  await page.keyboard.press('Escape');
  // Sampling is invoked only by a user click; the browser API itself is stubbed here.
  await page.evaluate(() => { window.EyeDropper = class { async open() { return { sRGBHex: '#bfe8de' }; } }; });
  await page.locator('#ctl-background-picker').click(); await page.locator('.colour-eyedropper').click();
  assert.equal(await page.evaluate(() => stickerApp.sceneSettings.background), '#bfe8de'); await page.keyboard.press('Escape');
  await page.evaluate(() => { window.EyeDropper = undefined; });
  await page.locator('[data-locale="zh-TW"]').click();
  await page.locator('#ctl-frameColor-picker').click();
  assert.equal(await page.locator('.colour-section-label').first().textContent(), '常用色盤'); assert(await page.locator('.colour-eyedropper').isHidden());
  await page.evaluate(() => I18N.setLocale('en')); assert(await picker.isHidden(), 'language rebuild closes stale controls');
  await page.keyboard.press('Escape');
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  mobile.on('pageerror', e => errors.push(e.message)); await mobile.route('https://**', r => r.abort());
  await mobile.goto(url); await mobile.waitForFunction(() => window.stickerApp);
  await mobile.evaluate(() => { I18N.setLocale('zh-TW'); stickerApp.addIcon('cloudface'); });
  await mobile.locator('#ctl-iconFill-picker').tap();
  const bounds = await mobile.locator('#colourPicker').boundingBox();
  assert(bounds.x >= 0 && bounds.x + bounds.width <= 390 && bounds.y >= 0 && bounds.y + bounds.height <= 844);
  const swatchBox = await mobile.locator('.colour-sv').boundingBox();
  await mobile.touchscreen.tap(swatchBox.x + 80, swatchBox.y + 50);
  await mobile.screenshot({ path: path.join(OUT, 'color-picker-mobile-zh.png') });
  await mobile.locator('.colour-hex').focus();
  await mobile.setViewportSize({ width: 390, height: 460 });
  await mobile.waitForFunction(() => {
    const p = document.querySelector('#colourPicker').getBoundingClientRect(), input = document.querySelector('.colour-hex').getBoundingClientRect();
    return p.top >= 0 && p.bottom <= innerHeight && input.top >= p.top && input.bottom <= p.bottom;
  });
  await mobile.locator('.colour-hex').fill('#bcd9f6'); await mobile.locator('.colour-hex').press('Enter');
  assert.equal(await mobile.evaluate(() => stickerApp.selected.settings.iconFill), '#bcd9f6', 'reduced keyboard-sized viewport keeps the active field visible');
  await mobile.setViewportSize({ width: 390, height: 844 });
  await mobile.locator('.colour-done').tap();
  const fallback = await browser.newPage(); await fallback.route('https://**', r => r.abort());
  await fallback.addInitScript(() => {
    HTMLElement.prototype.showPopover = undefined;
    window.nativePickerClicks = 0;
    const click = HTMLInputElement.prototype.click;
    HTMLInputElement.prototype.click = function() { if (this.type === 'color') window.nativePickerClicks++; else click.call(this); };
  });
  await fallback.goto(url); await fallback.waitForFunction(() => window.stickerApp);
  await fallback.evaluate(() => stickerApp.addIcon('cloudface')); await fallback.locator('#ctl-iconFill-picker').click();
  assert.equal(await fallback.evaluate(() => window.nativePickerClicks), 1, 'unsupported popover falls back to the native colour input');
  await fallback.close();
  await page.reload(); await page.waitForFunction(() => window.stickerApp);
  await page.evaluate(() => stickerApp.addIcon('heart')); await trigger.click();
  assert(await page.locator('.colour-recent .colour-swatch').count() > 0, 'recent swatches persist after reload');
  assert.deepEqual(errors, []);
  console.log('PASS hex/RGB validation, shade drag/keyboard, palette/recents, live updates, undo/redo, dismissal/focus, locks/selection, scene colours, sampling API, Chinese and touch bounds');
} finally { if (browser) await browser.close(); server.close(); }
