import assert from 'node:assert/strict';
import '../js/lanyard-physics.js';
const C=globalThis.StickerCord;
const create=()=>C.settle(C.create({x:320,y:410,width:260,height:330,arm:135,top:-30}));
const energy=s=>s.body.vx**2+s.body.vy**2+s.body.omega**2*10000;
const stretch=s=>Math.max(...s.ropes.flatMap((r,i)=>C.points(s,i).slice(1).map((p,j)=>Math.abs(Math.hypot(p.x-r[j].x,p.y-r[j].y)/s.lengths[i]-1))));
const run=hz=>{const s=create();s.body.vx=230;for(let i=0;i<hz*3;i++)C.advance(s,1/hz);return s;};
const a=run(30),b=run(60),c=run(120);
assert(Math.abs(a.body.x-b.body.x)<1e-6&&Math.abs(a.body.x-c.body.x)<1e-6,'fixed-step simulation is refresh-rate independent');
for(const key of ['pitch','yaw','pitchVelocity','yawVelocity'])assert(Math.abs(a.body[key]-b.body[key])<1e-8&&Math.abs(a.body[key]-c.body[key])<1e-8,'depth motion is refresh-rate independent');
const s=create(),anchors=structuredClone(s.anchors),initialY=s.body.y;
assert.equal(s.ropes.length,1,'one ribbon suspends the badge');
for(let i=0;i<90;i++)C.advance(s,1/60,{target:{x:470,y:240},gripX:60,gripY:60});
assert(s.body.x>350,'dragging pulls the hanging badge sideways');
assert(s.body.pitch>.05&&s.body.yaw>.1,'a lifted off-centre grab tilts and twists the badge');
assert(Math.abs(s.body.pitch)<=.48&&Math.abs(s.body.yaw)<=.72,'the photo remains front-facing');
const rope=C.points(s,0),first=rope[0],last=rope.at(-1),cross=p=>Math.abs((p.x-first.x)*(last.y-first.y)-(p.y-first.y)*(last.x-first.x))/Math.hypot(last.x-first.x,last.y-first.y);
assert(Math.max(...rope.map(cross))>1,'the cord bends independently under a lifted badge');
assert(stretch(s)<.09,'fabric does not stretch like rubber');
const released={...s.body};for(let i=0;i<20;i++)C.advance(s,1/60);
assert(Math.hypot(s.body.x-released.x,s.body.y-released.y)>8,'release carries momentum');
const early=energy(s);for(let i=0;i<60*15;i++)C.advance(s,1/60);
assert(energy(s)<early*.02,'swing energy decays');
assert(Math.abs(s.body.x-320)<3&&Math.abs(s.body.y-initialY)<3,'badge settles beneath the anchors');
assert.deepEqual(s.anchors,anchors,'anchors remain fixed');
assert(stretch(s)<.035,'settled cord keeps its length');
assert(Math.abs(s.body.pitch)<.001&&Math.abs(s.body.yaw)<.001,'pitch and twist settle without idle wobble');
const quiet=create();C.advance(quiet,.1,{target:{x:490,y:240},gripX:80,depthMotion:false});assert(quiet.body.pitch===0&&quiet.body.yaw===0,'reduced motion keeps the badge front-facing during a drag');
for(const hz of [15,144]){const z=create();for(let i=0;i<200;i++)C.advance(z,i%9===0?4:1/hz,{target:{x:i%2?10000:-10000,y:-3000}});assert(Object.values(z.body).every(Number.isFinite),'extreme drags and suspended tabs remain finite');}
console.log('PASS single-ribbon bending, limited stretch, tilt and twist, release momentum, settling, reduced depth motion, frame-rate independence and long-frame stability');
