import assert from 'node:assert/strict';
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = process.env.SHAKER_TEST_OUTPUT || path.join(ROOT, 'test/.out');
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const server = http.createServer((req, res) => {
  const file = path.join(ROOT, req.url.split('?')[0] === '/' ? 'index.html' : decodeURIComponent(req.url.split('?')[0]));
  if (!file.startsWith(ROOT + path.sep) || !fs.existsSync(file) || !fs.statSync(file).isFile()) { res.writeHead(404); return res.end(); }
  res.setHeader('Content-Type', ({ '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json' })[path.extname(file)] || 'application/octet-stream');
  fs.createReadStream(file).pipe(res);
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
let browser;
try {
  browser = await chromium.launch({ headless: true, args: ['--enable-unsafe-swiftshader'] });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.setDefaultTimeout(60000);
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.route('https://**', r => r.abort());
  await page.addInitScript(() => { try { localStorage.setItem('sticker-shader-editor:locale', 'en'); } catch {} });
  await page.goto(`http://127.0.0.1:${server.address().port}/`);
  await page.waitForFunction(() => window.stickerApp && document.querySelector('[data-tab="piknik"]'));
  await page.locator('#iconMenuWrap summary').click();
  await page.locator('#btnShaker').click();
  await page.waitForFunction(() => stickerApp.selected?.icon === 'shaker');
  assert(await page.locator('#shakerControls').isVisible());
  await page.evaluate(() => stickerApp.scene.stop());
  const id = await page.evaluate(() => stickerApp.selected.id);
  await page.locator('#shakerAdd').click();
  await page.locator('#iconSearch').fill('heart');
  await page.locator('button[data-icon="heart"]').click();
  assert.equal(await page.evaluate(() => stickerApp.selected.shakerItems.length), 1);
  const imageSrc = JSON.parse(fs.readFileSync(path.join(ROOT,'pixels/manifest.json'))).groups.find(g => g.collection === 'Pompompurin' && g.category === 'tiny').items[0].src;
  const piknik = JSON.parse(fs.readFileSync(path.join(ROOT,'assets/piknik/manifest.json'))).groups[0].items[0].src;
  await page.evaluate(async ({imageSrc,piknik}) => { await stickerApp.addPixel(imageSrc); await stickerApp.addPiknik(piknik); }, {imageSrc,piknik});
  assert.equal(await page.evaluate(() => stickerApp.selected.shakerItems.length), 3);
  await page.locator('.shaker-piece-remove').first().click();
  assert.equal(await page.evaluate(() => stickerApp.selected.shakerItems.length), 2);
  await page.evaluate(() => stickerApp.undo());
  assert.equal(await page.evaluate(() => stickerApp.selected.shakerItems.length), 3);
  await page.evaluate(() => { stickerApp.redo(); stickerApp.undo(); });
  await page.locator('#shakerShake').click();
  const report = await page.evaluate(() => {
    const a = stickerApp, r = a.selected, e = a.scene.get(r.id);
    const rest = e.shaker.bodies.map(b=>({...b})), texture=e.tex.img;
    for(let i=0;i<30;i++) a.scene._updateShaker(e,1/60);
    const moves=e.shaker.bodies.some((b,i)=>Math.hypot(b.x-rest[i].x,b.y-rest[i].y)>2);
    for(let i=0;i<300;i++) StickerShaker.advance(e.shaker,1/60);
    const stops=e.shaker.burst===0;
    const bodies = StickerShaker.simulate(17);
    return { frames: r.atlas.frames?.length || 0, moves, stops, reused:texture===e.tex.img,
      confined: bodies.every(frame => frame.every(b => Math.hypot(b.x,b.y) + b.r <= 28.801)) };
  });
  assert.equal(report.frames, 0); assert(report.moves && report.stops && report.confined && report.reused);
  await page.locator('#shakerLoop').check();
  await page.locator('#shakerColor').fill('#b7d9ef'); await page.locator('#shakerColor').dispatchEvent('change');
  assert.equal(await page.evaluate(() => stickerApp.selected.settings.shakerColor), '#b7d9ef');
  const guards = await page.evaluate(() => {
    const a=stickerApp,r=a.selected,e=a.scene.get(r.id),initial=r.shakerItems;
    const x = Math.round(r.work.width*.5-r.atlas.x0), y=Math.round(r.work.height*.5-r.atlas.y0);
    const alpha=a.scene.snapshot(e).getContext('2d').getImageData(x,y,1,1).data[3];
    const original=initial.slice(); r.shakerItems=Array.from({length:12},(_,i)=>initial[i%initial.length]);
    const before=a.history.undo.length; a.addIcon('star');
    const cap=r.shakerItems.length===12 && a.history.undo.length===before;
    r.shakerItems=original; e.locked=true; a.addIcon('star'); const lock=r.shakerItems.length===3; e.locked=false;
    e.settings.shakerLoop=true;
    const old=e.tex; a.scene.surfaceMotionPreference={matches:true};
    const beforeMotion=e.shaker.burst; a.scene._updateShaker(e,1/60);
    const reduced=e.shaker.burst<=beforeMotion && e.tex.img===old.img;
    a.scene.surfaceMotionPreference=matchMedia('(prefers-reduced-motion: reduce)');
    return {cap,lock,reduced,alpha};
  });
  assert(guards.cap && guards.lock && guards.reduced && guards.alpha>0 && guards.alpha<200);
  console.log('PASS mixed icon sources, remove/undo/redo, shake/settle, bounded physics and controls');
  const result = await page.evaluate(async id => {
    const a=stickerApp, r=a.records.get(id); a.scene.select(a.scene.get(id));
    const dup=a.duplicateSelected();
    const duplicateOK=dup.shakerItems.length===3;
    a.undo(); a.scene.select(a.scene.get(id));
    const loose=a.addIcon('star',{quiet:true});
    const target=a.scene.get(id), size=a.scene.size(target);
    const px=target.x + ((r.work.width*.5-r.atlas.x0)/r.atlas.w-.5)*size.w;
    const py=target.y + ((r.work.height*.63-r.atlas.y0)/r.atlas.h-.5)*size.h;
    const hit=a.scene.dropTargetFor(a.scene.get(loose.id),{x:px,y:py});
    const accepted=hit===target && a.scene.onDrop(a.scene.get(loose.id),target);
    const moved=accepted && !a.records.has(loose.id) && r.shakerItems.length===4;
    a.undo(); const restored=a.records.has(loose.id) && r.shakerItems.length===3;
    a.redo(); a.scene.select(a.scene.get(id));
    const animation=a.scene.animationFrames(a.scene.get(id),{size:256,fps:8,tilt:false});
    const gif=StickerAnim.encodeGIF(animation.frames,animation.fps);
    const apng=await StickerAnim.encodeAPNG(animation.frames,animation.fps);
    const png=a.scene.snapshot(a.scene.get(id));
    const {url}=await a.shareLink();
    return {duplicateOK,moved,restored,url,gif:Array.from(new Uint8Array(await gif.arrayBuffer())),apng:apng.size,png:png.toDataURL(),frame:animation.frames[4].toDataURL()};
  }, id);
  assert(result.duplicateOK && result.moved && result.restored && result.apng>100 && result.gif.length>100);
  fs.mkdirSync(OUT,{recursive:true});
  fs.writeFileSync(path.join(OUT,'shaker.gif'),Buffer.from(result.gif));
  fs.writeFileSync(path.join(OUT,'shaker.png'),Buffer.from(result.png.split(',')[1],'base64'));
  fs.writeFileSync(path.join(OUT,'shaker-moving.png'),Buffer.from(result.frame.split(',')[1],'base64'));
  await page.screenshot({path:path.join(OUT,'shaker-desktop.png')});
  await page.goto('about:blank'); await page.goto(result.url);
  await page.waitForFunction(() => window.stickerApp && [...stickerApp.records.values()].some(r=>r.icon==='shaker' && r.shakerItems.length===4));
  await page.evaluate(() => {const a=stickerApp; a.scene.stop();a.scene.select(a.scene.stickers.find(e=>e.settings.shaker)); I18N.setLocale('zh-TW');});
  assert.match(await page.locator('#shakerControls').getAttribute('aria-label'), /搖搖鑰匙圈/);
  const worker = await page.evaluate(() => { window.previousShakerAtlas = stickerApp.selected.atlas; stickerApp.composeRecord(stickerApp.selected); return stickerApp.state.composeMode; });
  await page.waitForFunction(() => stickerApp.selected.atlas !== window.previousShakerAtlas);
  assert.equal(await page.evaluate(() => stickerApp.selected.atlas.frames?.length || 0), 0);
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(OUT,'shaker-mobile.png')});
  await page.locator('#shakerShake').click();
  await page.locator('#shakerAdd').click();
  assert(await page.locator('#iconSearch').isVisible());
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  assert.deepEqual(errors, []);
  console.log(`PASS duplicate, move inside and undo, PNG/GIF/APNG export, fresh share reload, ${worker} composition, Chinese and mobile controls`);
} finally { if(browser) await browser.close();server.close(); }
